In [1]:
import numpy as np
import pandas as pd
a = ([10,20,30,40])
print(a)

[10, 20, 30, 40]

In [2]:
df = pd.read_csv("Sample - Superstore - full.csv", encoding = 'latin-1')
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2016-138688,12-06-2016,16-06-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,CA-2014-110422,21-01-2014,23-01-2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,CA-2017-119914,04-05-2017,09-05-2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [3]:
del_data = df.drop(columns= ['Order ID','Customer ID'])
#del_data

In [4]:
print('Print after deleted columns......')
del_data.head(10)

Print after deleted columns......

,Order Date,Ship Date,Ship Mode,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,08-11-2016,11-11-2016,Second Class,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,08-11-2016,11-11-2016,Second Class,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,12-06-2016,16-06-2016,Second Class,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,11-10-2015,18-10-2015,Standard Class,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,11-10-2015,18-10-2015,Standard Class,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,09-06-2014,14-06-2014,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,09-06-2014,14-06-2014,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,09-06-2014,14-06-2014,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,09-06-2014,14-06-2014,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,09-06-2014,14-06-2014,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

In [5]:
sel_data = df[['Region','Sales']]
print("Region and Sales columns.....")
sel_data.head(10)

Region and Sales columns.....

  Region     Sales
0  South  261.9600
1  South  731.9400
2   West   14.6200
3  South  957.5775
4  South   22.3680
5   West   48.8600
6   West    7.2800
7   West  907.1520
8   West   18.5040
9   West  114.9000

In [6]:
df.drop([9993,90,48,], axis=0,inplace = True)
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2016-138688,12-06-2016,16-06-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9988,CA-2017-163629,17-11-2017,21-11-2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,Georgia,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.1000,5,0.00,55.6470
9989,CA-2014-110422,21-01-2014,23-01-2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,CA-2017-121258,26-02-2017,03-03-2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200

In [7]:
df = pd.read_csv('diamonds.csv')
df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [8]:
sel_data = df[ (df['cut'] == 'Premium') & (df['carat'] >= 0.50) & (df['price']>2500) ]
sel_data

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
99,100,0.80,Premium,H,SI1,61.5,58.0,2760,5.97,5.93,3.66
101,102,0.75,Premium,E,SI1,59.9,54.0,2760,6.00,5.96,3.58
103,104,0.75,Premium,G,VS2,61.7,58.0,2760,5.85,5.79,3.59
106,107,0.80,Premium,G,SI1,63.0,59.0,2760,5.90,5.81,3.69
112,113,0.90,Premium,I,VS2,63.0,58.0,2761,6.16,6.12,3.87
...,...,...,...,...,...,...,...,...,...,...,...
53928,53929,0.79,Premium,E,SI2,61.4,58.0,2756,6.03,5.96,3.68
53930,53931,0.71,Premium,E,SI1,60.5,55.0,2756,5.79,5.74,3.49
53931,53932,0.71,Premium,F,SI1,59.8,62.0,2756,5.74,5.73,3.43
53934,53935,0.72,Premium,D,SI1,62.7,59.0,2757,5.69,5.73,3.58
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74

### Example of log and iloc

In [9]:
loc_data = df.loc[20:100,['cut','price']]
loc_data

           cut  price
20        Good    351
21   Very Good    352
22   Very Good    353
23   Very Good    353
24   Very Good    353
..         ...    ...
96        Good   2759
97        Fair   2759
98   Very Good   2760
99     Premium   2760
100  Very Good   2760

[81 rows x 2 columns]

In [10]:
iloc_data = df.iloc[20:100,3:10]
iloc_data

   color clarity  depth  table  price     x     y
20     I     SI2   63.3   56.0    351  4.26  4.30
21     E     VS2   63.8   55.0    352  3.85  3.92
22     H     VS1   61.0   57.0    353  3.94  3.96
23     J     SI1   59.4   62.0    353  4.39  4.43
24     J     SI1   58.1   62.0    353  4.44  4.47
..   ...     ...    ...    ...    ...   ...   ...
95     E     VS2   57.5   58.0   2759  5.85  5.90
96     F     VS1   59.4   62.0   2759  5.71  5.76
97     F     SI2   66.3   62.0   2759  6.27  5.95
98     E     SI1   61.6   59.0   2760  5.77  5.78
99     H     SI1   61.5   58.0   2760  5.97  5.93

[80 rows x 7 columns]

In [11]:
df['increment_price'] = (df['price']*20)/100 + df['price']
df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,increment_price
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,391.2
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,391.2
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,392.4
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,400.8
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,402.0
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,3308.4
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,3308.4
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,3308.4
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,3308.4
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,3308.4

In [12]:
df1 = pd.DataFrame({"name":['Abc', 'cde', 'xyz'],
                  "toy":[np.nan, 'Car', 'Bike'],
                  "born":[pd.NaT, pd.Timestamp("2000-09-05"),None]})
df1

  name   toy       born
0  Abc   NaN        NaT
1  cde   Car 2000-09-05
2  xyz  Bike        NaT

In [13]:
df1.dropna()

  name  toy       born
1  cde  Car 2000-09-05

In [14]:
df2 = pd.DataFrame([[1, 2, np.nan],
                  [np.nan, np.nan, np.nan],
                  [pd.NaT, 3,None]],
                  columns = ["A","B","C"])
df2

     A    B   C
0    1  2.0 NaN
1  NaN  NaN NaN
2  NaT  3.0 NaN

In [15]:
df3 = df2.fillna(df2.mean())
df3

C:\Users\Hp\AppData\Local\Temp\ipykernel_12620\4247997979.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df3 = df2.fillna(df2.mean())

     A    B   C
0  1.0  2.0 NaN
1  1.0  2.5 NaN
2  1.0  3.0 NaN

In [16]:
df2 = pd.DataFrame([[1, 2, np.nan,None],
                  [np.nan, np.nan, np.nan,pd.NaT],
                  [pd.NaT, 3,None,np.nan],
                   [2,4,None,np.nan]],
                  columns = ["A","B","C","D"])
df2

     A    B   C   D
0    1  2.0 NaN NaT
1  NaN  NaN NaN NaT
2  NaT  3.0 NaN NaT
3    2  4.0 NaN NaT

In [17]:
df2['A'].fillna(df2['A'].mean(), inplace = True)
df2['D'].fillna("-", inplace = True)
df2

C:\Users\Hp\AppData\Local\Temp\ipykernel_12620\3286629556.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['A'].fillna(df2['A'].mean(), inplace = True)
C:\Users\Hp\AppData\Local\Temp\ipykernel_12620\3286629556.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['A'].fillna(df2['A'].mean(), inplace = True)
C:\Users\Hp\AppData\Local\Temp\ipykernel_12620\3286629556.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['D'].fillna("-", inplace = True)
C:\Users\Hp\AppData\Local\Temp\ipykernel_12620\3286629556.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  df2['D'].fillna("-", inplace = True)

     A    B   C  D
0  1.0  2.0 NaN  -
1  1.5  NaN NaN  -
2  1.5  3.0 NaN  -
3  2.0  4.0 NaN  -

In [18]:
df2['A'] = df2['A'].fillna(df2['A'].mean())
df2['C'] = df2['C'].fillna("-")
df2

     A    B  C  D
0  1.0  2.0  -  -
1  1.5  NaN  -  -
2  1.5  3.0  -  -
3  2.0  4.0  -  -

### Multi Indexing

In [19]:
index1 = [('Delhi',2010),('Delhi',2020),('Surat',2010),('Surat',2020),('Valsad',2010),('Valsad',2020)]

population = [2392838,29829839,30903903,232303080,320498323,293488402]

pop = pd.Series(population, name = 'Population',index = index1)

pop

(Delhi, 2010)       2392838
(Delhi, 2020)      29829839
(Surat, 2010)      30903903
(Surat, 2020)     232303080
(Valsad, 2010)    320498323
(Valsad, 2020)    293488402
Name: Population, dtype: int64

In [20]:
C = [('A',1),('A',2),('A',3),('B',1),('B',2),('B',3)]
R = [1,2,3,1,2,3]
M = [20,30,25,26,34,22]

Class = pd.Series(C,name = 'Class', index = C)
Roll = pd.Series(R,name = 'Roll No', index = C)
Marks = pd.Series(M,name = 'Marks', index = C)

Roll
Marks

(A, 1)    20
(A, 2)    30
(A, 3)    25
(B, 1)    26
(B, 2)    34
(B, 3)    22
Name: Marks, dtype: int64

In [21]:
product = [['A','B'],[1,2,3]]
# array = [['A','A','A','B','B','B'],[1,2,3,1,2,3]]
# tuples = [('A',1),('A',2),('A',3),('B',1),('B',2),('B',3)]


index1 = pd.MultiIndex.from_product(product, names = ('Class','Roll No'))
# index1 = pd.MultiIndex.from_arrays(array, names = ('Class','Roll No'))
# index1 = pd.MultiIndex.from_tuples(tuples, names = ('Class','Roll No'))

df = pd.DataFrame({'Marks':[10,20,30,40,50,60]}, index = index1)

df

               Marks
Class Roll No
A     1           10
      2           20
      3           30
B     1           40
      2           50
      3           60

In [22]:
# df = df.droplevel('Class')
# df = df.droplevel('Roll No')
df

               Marks
Class Roll No
A     1           10
      2           20
      3           30
B     1           40
      2           50
      3           60

In [23]:
df = df.reset_index()
df

  Class  Roll No  Marks
0     A        1     10
1     A        2     20
2     A        3     30
3     B        1     40
4     B        2     50
5     B        3     60

In [24]:
# df.transpose()
# df1 = df.transpose()
df

  Class  Roll No  Marks
0     A        1     10
1     A        2     20
2     A        3     30
3     B        1     40
4     B        2     50
5     B        3     60

In [25]:
df.T

          0   1   2   3   4   5
Class     A   A   A   B   B   B
Roll No   1   2   3   1   2   3
Marks    10  20  30  40  50  60

In [26]:
df = pd.read_csv('diamonds.csv')
df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [27]:
df1 = df.rename(columns={'carat':'Carat','cut':'Cut','clarity':'Clarity','depth':'Depth','table':'Table','price':'Price'})
df1

,Unnamed: 0,Carat,Cut,color,Clarity,Depth,Table,Price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [28]:
df1 = df1.sort_values(by='Price',ascending=False)
df1

,Unnamed: 0,Carat,Cut,color,Clarity,Depth,Table,Price,x,y,z
27749,27750,2.29,Premium,I,VS2,60.8,60.0,18823,8.50,8.47,5.16
27748,27749,2.00,Very Good,G,SI1,63.5,56.0,18818,7.90,7.97,5.04
27747,27748,1.51,Ideal,G,IF,61.7,55.0,18806,7.37,7.41,4.56
27746,27747,2.07,Ideal,G,SI2,62.5,55.0,18804,8.20,8.13,5.11
27745,27746,2.00,Very Good,H,SI1,62.8,57.0,18803,7.95,8.00,5.01
...,...,...,...,...,...,...,...,...,...,...,...
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43

In [29]:
df1 = df1.sort_values(by=['x','y','z'],ascending=[True,True,True])
df1

,Unnamed: 0,Carat,Cut,color,Clarity,Depth,Table,Price,x,y,z
27429,27430,2.25,Premium,H,SI2,62.8,59.0,18034,0.00,0.00,0.00
26243,26244,1.20,Premium,D,VVS1,62.1,59.0,15686,0.00,0.00,0.00
24520,24521,1.56,Ideal,G,VS2,62.2,54.0,12800,0.00,0.00,0.00
15951,15952,1.14,Fair,G,VS1,57.5,67.0,6381,0.00,0.00,0.00
11963,11964,1.00,Very Good,H,VS2,63.3,53.0,5139,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...
26444,26445,4.00,Very Good,I,I1,63.3,58.0,15984,10.01,9.94,6.31
25999,26000,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24
25998,25999,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17
27630,27631,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72
27415,27416,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98

In [30]:
df2 = df1.set_index('Unnamed: 0')
df2

,Carat,Cut,color,Clarity,Depth,Table,Price,x,y,z
Unnamed: 0,,,,,,,,,,
27430,2.25,Premium,H,SI2,62.8,59.0,18034,0.00,0.00,0.00
26244,1.20,Premium,D,VVS1,62.1,59.0,15686,0.00,0.00,0.00
24521,1.56,Ideal,G,VS2,62.2,54.0,12800,0.00,0.00,0.00
15952,1.14,Fair,G,VS1,57.5,67.0,6381,0.00,0.00,0.00
11964,1.00,Very Good,H,VS2,63.3,53.0,5139,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...
26445,4.00,Very Good,I,I1,63.3,58.0,15984,10.01,9.94,6.31
26000,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24
25999,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17
27631,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72
27416,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98

In [31]:
df1 = df1.groupby('Cut')['Price'].sum()
df1

Cut
Fair          7017600
Good         19275009
Ideal        74513487
Premium      63221498
Very Good    48107623
Name: Price, dtype: int64

In [32]:
# df1 = df.groupby('cut')['price'].agg('sum','min','mix','mean','count')
df1 = df.groupby('cut')['price'].agg('min','max')
df1

cut
Fair         337
Good         327
Ideal        326
Premium      326
Very Good    336
Name: price, dtype: int64

In [33]:
sel_data = df[ (df['color'] == 'D') | (df['color'] == 'E') | (df['color'] == 'F')] 
sel_data

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
8,9,0.22,Fair,E,VS2,65.1,61.0,337,3.87,3.78,2.49
12,13,0.22,Premium,F,SI1,60.4,61.0,342,3.88,3.84,2.33
...,...,...,...,...,...,...,...,...,...,...,...
53934,53935,0.72,Premium,D,SI1,62.7,59.0,2757,5.69,5.73,3.58
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [34]:
sel_data1 = sel_data[sel_data['carat']>0.5]
sel_data1

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
90,91,0.70,Ideal,E,SI1,62.5,57.0,2757,5.70,5.72,3.57
91,92,0.86,Fair,E,SI2,55.1,69.0,2757,6.45,6.33,3.52
93,94,0.71,Very Good,E,VS2,62.4,57.0,2759,5.68,5.73,3.56
95,96,0.70,Good,E,VS2,57.5,58.0,2759,5.85,5.90,3.38
96,97,0.70,Good,F,VS1,59.4,62.0,2759,5.71,5.76,3.40
...,...,...,...,...,...,...,...,...,...,...,...
53934,53935,0.72,Premium,D,SI1,62.7,59.0,2757,5.69,5.73,3.58
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [35]:
sel_data3 = sel_data1.groupby(['color','cut'])['price'].sum().reset_index()
sel_data3

   color        cut     price
0      D       Fair    671321
1      D       Good   2059181
2      D      Ideal   6113282
3      D    Premium   5240744
4      D  Very Good   4763608
5      E       Fair    773805
6      E       Good   2934349
7      E      Ideal   8293875
8      E    Premium   7398875
9      E  Very Good   6953085
10     F       Fair   1140537
11     F       Good   2950441
12     F      Ideal  11396594
13     F    Premium   9431780
14     F  Very Good   7603124

In [38]:
sel_data4 = sel_data3.sort_values(by=['color','price'],ascending=[False,True])
sel_data4 = sel_data4.rename(columns={'color':'COLOR','cut':'CUT','price':'PRICE'})
sel_data4

   COLOR        CUT     PRICE
10     F       Fair   1140537
11     F       Good   2950441
14     F  Very Good   7603124
13     F    Premium   9431780
12     F      Ideal  11396594
5      E       Fair    773805
6      E       Good   2934349
9      E  Very Good   6953085
8      E    Premium   7398875
7      E      Ideal   8293875
0      D       Fair    671321
1      D       Good   2059181
4      D  Very Good   4763608
3      D    Premium   5240744
2      D      Ideal   6113282

In [ ]:
# df1 = df.groupby
df1 = df.groupby(['cut','color']).agg({'price':['sum','mean'],'depth':'mean'})
df1