### Diamond Data Task

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('diamonds.csv')

df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [3]:
df['Carat_Between'] = np.where(df['carat']<0.2,"Less then 0.2",
                      np.where(df['carat']<0.5,"0.2 - 0.5",
                      np.where(df['carat']<1,"0.5 - 1","1+")))
df

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,Carat_Between
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,0.2 - 0.5
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,0.2 - 0.5
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,0.2 - 0.5
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,0.2 - 0.5
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,0.2 - 0.5
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,0.5 - 1
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,0.5 - 1
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,0.5 - 1
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,0.5 - 1
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,0.5 - 1

### main file data task

In [4]:
df = pd.read_excel('Main file.xlsx')
df.drop_duplicates()
df

,ShipmentID,SPID,Sales_person,Team,Picture,PID,Product,Category,Cost_per_box,GID,Geo,Region,Shipdate,Amount,Boxes,Order_Status
0,S00000012,SP01,Barr Faughny,Yummies,https://files.chandoo.org/pbix/img/circle/men-...,P01,Milk Bars,Bars,5.26,G5,Australia,APAC,2023-12-12,5609.25,374,Delivered
1,S00000042,SP01,Barr Faughny,Yummies,https://files.chandoo.org/pbix/img/circle/men-...,P01,Milk Bars,Bars,5.26,G4,New Zealand,APAC,2023-10-26,7197.75,450,Delivered
2,S00000058,SP01,Barr Faughny,Yummies,https://files.chandoo.org/pbix/img/circle/men-...,P01,Milk Bars,Bars,5.26,G3,Canada,Americas,2024-06-28,13279.50,1107,Delivered
3,S00000088,SP01,Barr Faughny,Yummies,https://files.chandoo.org/pbix/img/circle/men-...,P02,50% Dark Bites,Bites,7.48,G1,India,APAC,2023-04-03,1919.25,138,Delivered
4,S00000095,SP01,Barr Faughny,Yummies,https://files.chandoo.org/pbix/img/circle/men-...,P02,50% Dark Bites,Bites,7.48,G5,Australia,APAC,2023-12-25,2324.25,146,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7900,S00191176,SP21,Camilla Castle,Tempo,https://files.chandoo.org/pbix/img/circle/wome...,P22,Peanut Butter Cubes,Bites,2.65,G5,Australia,APAC,2023-09-08,8538.75,427,Delivered
7901,S00191181,SP21,Camilla Castle,Tempo,https://files.chandoo.org/pbix/img/circle/wome...,P22,Peanut Butter Cubes,Bites,2.65,G6,UK,Europe,2023-02-01,11569.50,579,Delivered
7902,S00191195,SP21,Camilla Castle,Tempo,https://files.chandoo.org/pbix/img/circle/wome...,P22,Peanut Butter Cubes,Bites,2.65,G6,UK,Europe,2024-06-17,6014.25,335,Delivered
7903,S00191196,SP21,Camilla Castle,Tempo,https://files.chandoo.org/pbix/img/circle/wome...,P22,Peanut Butter Cubes,Bites,2.65,G6,UK,Europe,2023-06-14,8696.25,484,Delivered
7904,S00191241,SP21,Camilla Castle,Tempo,https://files.chandoo.org/pbix/img/circle/wome...,P22,Peanut Butter Cubes,Bites,2.65,G4,New Zealand,APAC,2024-06-03,9654.75,537,Delivered

In [5]:
import openpyxl
df1 = pd.read_excel('sample-chocolate-sales-data-all - Copy.xlsx', sheet_name='Shipments')
df1

     ShipmentID  SPID  PID GID   Shipdate    Amount  Boxes Order_Status
0     S00000012  SP01  P01  G5 2023-12-12   5609.25    374    Delivered
1     S00000042  SP01  P01  G4 2023-10-26   7197.75    450    Delivered
2     S00000058  SP01  P01  G3 2024-06-28  13279.50   1107    Delivered
3     S00000088  SP01  P02  G1 2023-04-03   1919.25    138    Delivered
4     S00000095  SP01  P02  G5 2023-12-25   2324.25    146    Delivered
...         ...   ...  ...  ..        ...       ...    ...          ...
7900  S00191176  SP21  P22  G5 2023-09-08   8538.75    427    Delivered
7901  S00191181  SP21  P22  G6 2023-02-01  11569.50    579    Delivered
7902  S00191195  SP21  P22  G6 2024-06-17   6014.25    335    Delivered
7903  S00191196  SP21  P22  G6 2023-06-14   8696.25    484    Delivered
7904  S00191241  SP21  P22  G4 2024-06-03   9654.75    537    Delivered

[7905 rows x 8 columns]

In [6]:
df1.drop_duplicates()

     ShipmentID  SPID  PID GID   Shipdate    Amount  Boxes Order_Status
0     S00000012  SP01  P01  G5 2023-12-12   5609.25    374    Delivered
1     S00000042  SP01  P01  G4 2023-10-26   7197.75    450    Delivered
2     S00000058  SP01  P01  G3 2024-06-28  13279.50   1107    Delivered
3     S00000088  SP01  P02  G1 2023-04-03   1919.25    138    Delivered
4     S00000095  SP01  P02  G5 2023-12-25   2324.25    146    Delivered
...         ...   ...  ...  ..        ...       ...    ...          ...
7900  S00191176  SP21  P22  G5 2023-09-08   8538.75    427    Delivered
7901  S00191181  SP21  P22  G6 2023-02-01  11569.50    579    Delivered
7902  S00191195  SP21  P22  G6 2024-06-17   6014.25    335    Delivered
7903  S00191196  SP21  P22  G6 2023-06-14   8696.25    484    Delivered
7904  S00191241  SP21  P22  G4 2024-06-03   9654.75    537    Delivered

[7905 rows x 8 columns]

In [7]:
df2 = pd.read_excel('sample-chocolate-sales-data-all - Copy.xlsx', sheet_name='Product')
df2

                 Product Category  Cost_per_box  PID
0              Milk Bars     Bars          5.26  P01
1         50% Dark Bites    Bites          7.48  P02
2           Almond Choco     Bars          5.15  P03
3        Raspberry Choco     Bars          3.85  P04
4        Mint Chip Choco     Bars          5.72  P05
5                Eclairs    Bites          6.31  P06
6          Drinking Coco    Other          9.94  P07
7        99% Dark & Pure     Bars          7.73  P08
8           Orange Choco     Bars          3.68  P09
9    Spicy Special Slims    Bites          8.22  P10
10           After Nines    Bites         10.23  P11
11      Fruit & Nut Bars     Bars          4.74  P12
12         85% Dark Bars     Bars         10.51  P13
13            White Choc    Other          6.43  P14
14   Baker's Choco Chips     Bars         12.41  P15
15   Organic Choco Syrup    Other          9.57  P16
16  Caramel Stuffed Bars     Bars          8.43  P17
17    Manuka Honey Choco    Other          6.80  P18
18        70% Dark Bites    Bites          5.04  P19
19    Smooth Silky Salty     Bars          2.76  P20
20  Choco Coated Almonds    Bites          3.32  P21
21   Peanut Butter Cubes    Bites          2.65  P22

In [8]:
df3 = pd.read_excel('sample-chocolate-sales-data-all - Copy.xlsx', sheet_name='Sales')
df3

,Sales_person,Team,Picture,SPID
0,Barr Faughny,Yummies,https://files.chandoo.org/pbix/img/circle/men-...,SP01
1,Dennison Crosswaite,Yummies,https://files.chandoo.org/pbix/img/circle/men-...,SP02
2,Gunar Cockshoot,Yummies,https://files.chandoo.org/pbix/img/circle/men-...,SP03
3,Curtice Advani,Delish,https://files.chandoo.org/pbix/img/circle/men-...,SP04
4,Kaine Padly,Delish,https://files.chandoo.org/pbix/img/circle/men-...,SP05
5,Ches Bonnell,Delish,https://files.chandoo.org/pbix/img/circle/men-...,SP06
6,Brien Boise,Delish,https://files.chandoo.org/pbix/img/circle/men-...,SP07
7,Husein Augar,Delish,https://files.chandoo.org/pbix/img/circle/men-...,SP08
8,Beverie Moffet,Jucies,https://files.chandoo.org/pbix/img/circle/men-...,SP09
9,Oby Sorrel,Jucies,https://files.chandoo.org/pbix/img/circle/men-...,SP10
10,Wilone O'Kielt,Yummies,https://files.chandoo.org/pbix/img/circle/men-...,SP11
11,Gigi Bohling,Yummies,https://files.chandoo.org/pbix/img/circle/wome...,SP12
12,Andria Kimpton,Delish,https://files.chandoo.org/pbix/img/circle/wome...,SP13
13,Karlen McCaffrey,Delish,https://files.chandoo.org/pbix/img/circle/wome...,SP14
14,Jan Morforth,Yummies,https://files.chandoo.org/pbix/img/circle/wome...,SP15
15,Dotty Strutley,Jucies,https://files.chandoo.org/pbix/img/circle/wome...,SP16
16,Kelci Walkden,Jucies,https://files.chandoo.org/pbix/img/circle/wome...,SP17
17,Marney O'Breen,Jucies,https://files.chandoo.org/pbix/img/circle/wome...,SP18
18,Rafaelita Blaksland,Jucies,https://files.chandoo.org/pbix/img/circle/wome...,SP19
19,Madelene Upcott,Jucies,https://files.chandoo.org/pbix/img/circle/wome...,SP20
20,Camilla Castle,Tempo,https://files.chandoo.org/pbix/img/circle/wome...,SP21
21,Jehu Rudeforth,Tempo,https://files.chandoo.org/pbix/img/circle/wome...,SP22
22,Mallorie Waber,Tempo,https://files.chandoo.org/pbix/img/circle/men-...,SP23
23,Van Tuxwell,Tempo,https://files.chandoo.org/pbix/img/circle/men-...,SP24
24,Roddy Speechley,Tempo,https://files.chandoo.org/pbix/img/circle/men-...,SP25

In [9]:
df4 = pd.read_excel('sample-chocolate-sales-data-all - Copy.xlsx', sheet_name='Geo')
df4

           Geo    Region GID
0        India      APAC  G1
1          USA  Americas  G2
2       Canada  Americas  G3
3  New Zealand      APAC  G4
4    Australia      APAC  G5
5           UK    Europe  G6

### Location Wise Total Sales

In [10]:
data = pd.merge(df1,df4, on='GID',how='inner')
data = df.groupby(['Region','Geo'])['Amount'].sum().reset_index(name='Total_Sales').sort_values(by = 'Total_Sales',ascending=False)
data

     Region          Geo  Total_Sales
5    Europe           UK  10541805.75
1      APAC        India  10393677.00
4  Americas          USA   7896249.00
0      APAC    Australia   7809234.75
2      APAC  New Zealand   5392820.25
3  Americas       Canada   2658602.25

### Product wise Total Costing and Total Sales

In [11]:
df5 = pd.merge(df1,df2, on='PID', how='inner')
df5

,ShipmentID,SPID,PID,GID,Shipdate,Amount,Boxes,Order_Status,Product,Category,Cost_per_box
0,S00000012,SP01,P01,G5,2023-12-12,5609.25,374,Delivered,Milk Bars,Bars,5.26
1,S00000042,SP01,P01,G4,2023-10-26,7197.75,450,Delivered,Milk Bars,Bars,5.26
2,S00000058,SP01,P01,G3,2024-06-28,13279.50,1107,Delivered,Milk Bars,Bars,5.26
3,S00000088,SP01,P02,G1,2023-04-03,1919.25,138,Delivered,50% Dark Bites,Bites,7.48
4,S00000095,SP01,P02,G5,2023-12-25,2324.25,146,Delivered,50% Dark Bites,Bites,7.48
...,...,...,...,...,...,...,...,...,...,...,...
7900,S00191176,SP21,P22,G5,2023-09-08,8538.75,427,Delivered,Peanut Butter Cubes,Bites,2.65
7901,S00191181,SP21,P22,G6,2023-02-01,11569.50,579,Delivered,Peanut Butter Cubes,Bites,2.65
7902,S00191195,SP21,P22,G6,2024-06-17,6014.25,335,Delivered,Peanut Butter Cubes,Bites,2.65
7903,S00191196,SP21,P22,G6,2023-06-14,8696.25,484,Delivered,Peanut Butter Cubes,Bites,2.65
7904,S00191241,SP21,P22,G4,2024-06-03,9654.75,537,Delivered,Peanut Butter Cubes,Bites,2.65

In [12]:
df5['Total_costing'] = df['Cost_per_box'] * df['Boxes']
df5

,ShipmentID,SPID,PID,GID,Shipdate,Amount,Boxes,Order_Status,Product,Category,Cost_per_box,Total_costing
0,S00000012,SP01,P01,G5,2023-12-12,5609.25,374,Delivered,Milk Bars,Bars,5.26,1967.24
1,S00000042,SP01,P01,G4,2023-10-26,7197.75,450,Delivered,Milk Bars,Bars,5.26,2367.00
2,S00000058,SP01,P01,G3,2024-06-28,13279.50,1107,Delivered,Milk Bars,Bars,5.26,5822.82
3,S00000088,SP01,P02,G1,2023-04-03,1919.25,138,Delivered,50% Dark Bites,Bites,7.48,1032.24
4,S00000095,SP01,P02,G5,2023-12-25,2324.25,146,Delivered,50% Dark Bites,Bites,7.48,1092.08
...,...,...,...,...,...,...,...,...,...,...,...,...
7900,S00191176,SP21,P22,G5,2023-09-08,8538.75,427,Delivered,Peanut Butter Cubes,Bites,2.65,1131.55
7901,S00191181,SP21,P22,G6,2023-02-01,11569.50,579,Delivered,Peanut Butter Cubes,Bites,2.65,1534.35
7902,S00191195,SP21,P22,G6,2024-06-17,6014.25,335,Delivered,Peanut Butter Cubes,Bites,2.65,887.75
7903,S00191196,SP21,P22,G6,2023-06-14,8696.25,484,Delivered,Peanut Butter Cubes,Bites,2.65,1282.60
7904,S00191241,SP21,P22,G4,2024-06-03,9654.75,537,Delivered,Peanut Butter Cubes,Bites,2.65,1423.05

In [13]:
df6 = df5.groupby('Product')[['Total_costing','Amount']].sum().reset_index().sort_values(by=['Total_costing','Amount'],ascending=[True,False])
df6

                 Product  Total_costing      Amount
15          Orange Choco      117336.80   655830.00
10               Eclairs      174578.77   713364.75
0         50% Dark Bites      190313.64   380517.75
1         70% Dark Bites      237091.68  1261723.50
5           Almond Choco      275797.95   579559.50
17   Peanut Butter Cubes      500049.70  3745316.25
19    Smooth Silky Salty      517450.32  1835129.25
4            After Nines      650771.22  1195256.25
6    Baker's Choco Chips      664083.92   995901.75
8   Choco Coated Almonds      674896.24  1810901.25
21            White Choc      736871.57  1813655.25
11      Fruit & Nut Bars      758997.24  2373918.75
13             Milk Bars      872576.14  2293260.75
9          Drinking Coco      889202.58  2319192.00
3        99% Dark & Pure     1110646.40  2846004.75
16   Organic Choco Syrup     1681429.86  2787086.25
20   Spicy Special Slims     1763576.34  2981648.25
14       Mint Chip Choco     1836972.28  2157543.00
18       Raspberry Choco     1848604.45  3283098.75
7   Caramel Stuffed Bars     1959089.85  2020992.75
12    Manuka Honey Choco     2674528.40  3495795.75
2          85% Dark Bars     4317655.14  3146692.50

### Top 5 most selling product

In [17]:
df7 = pd.merge(df1,df2,on='PID',how='left')
df7.drop_duplicates()
df7 = df7.groupby('Product')['Product'].count().reset_index(name = "Total_Product_Sold")
df7.head(5)
df7.sort_values(by= 'Total_Product_Sold', ascending=False).head(5)

                Product  Total_Product_Sold
18      Raspberry Choco                 637
2         85% Dark Bars                 608
20  Spicy Special Slims                 608
17  Peanut Butter Cubes                 552
14      Mint Chip Choco                 529

### Shipment table tasks

In [16]:
ship_status = df1.drop_duplicates()
ship_status = df1.groupby('Order_Status')['Order_Status'].count().reset_index(name='Order_Count').sort_values(by="Order_Count", ascending=False)
ship_status

  Order_Status  Order_Count
1    Delivered         6356
3      Shipped          793
2       Placed          385
0    Cancelled          371